#!/bin/bash
#
# Reporter
# Generates HTML, JSON, and Markdown reports
#

set -euo pipefail

INPUT_DIR="$1"
OUTPUT_DIR="$2"
TARGET="$3"

if [[ -z "$INPUT_DIR" ]] || [[ -z "$OUTPUT_DIR" ]] || [[ -z "$TARGET" ]]; then
    echo "Usage: $0 <input_dir> <output_dir> <target>"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

TIMESTAMP=$(date -Iseconds)
DATE_HUMAN=$(date '+%Y-%m-%d %H:%M:%S')

# Gather stats
SUBDOMAINS=0
ALIVE_HOSTS=0
OPEN_PORTS=0
VULNS=0

[[ -f "$INPUT_DIR/raw/subdomains.txt" ]] && SUBDOMAINS=$(wc -l < "$INPUT_DIR/raw/subdomains.txt" 2>/dev/null || echo 0)
[[ -f "$INPUT_DIR/raw/alive_urls.txt" ]] && ALIVE_HOSTS=$(wc -l < "$INPUT_DIR/raw/alive_urls.txt" 2>/dev/null || echo 0)
[[ -f "$INPUT_DIR/raw/ports.json" ]] && OPEN_PORTS=$(grep -c '"open": true' "$INPUT_DIR/raw/ports.json" 2>/dev/null || echo 0)
[[ -f "$INPUT_DIR/vulnerabilities/nuclei.json" ]] && VULNS=$(grep -c '"template"' "$INPUT_DIR/vulnerabilities/nuclei.json" 2>/dev/null || echo 0)

echo "[reporter] Generating reports for $TARGET"

# =============================================================================
# JSON REPORT
# =============================================================================

cat > "$OUTPUT_DIR/report.json" << EOF
{
  "target": "$TARGET",
  "timestamp": "$TIMESTAMP",
  "statistics": {
    "subdomains_found": $SUBDOMAINS,
    "live_hosts": $ALIVE_HOSTS,
    "open_ports": $OPEN_PORTS,
    "vulnerabilities": $VULNS
  },
  "files": {
    "subdomains": "raw/subdomains.txt",
    "alive_urls": "raw/alive_urls.txt",
    "ports": "raw/ports.json",
    "vulnerabilities": "vulnerabilities/nuclei.json"
  }
}
EOF

# =============================================================================
# MARKDOWN REPORT
# =============================================================================

cat > "$OUTPUT_DIR/report.md" << EOF
# Reconnaissance Report: $TARGET

**Generated:** $DATE_HUMAN

---

## Summary

| Metric | Count |
|--------|-------|
| Subdomains Found | $SUBDOMAINS |
| Live Hosts | $ALIVE_HOSTS |
| Open Ports | $OPEN_PORTS |
| Vulnerabilities | $VULNS |

---

## Subdomains

EOF

if [[ -f "$INPUT_DIR/raw/subdomains.txt" ]] && [[ -s "$INPUT_DIR/raw/subdomains.txt" ]]; then
    echo '```' >> "$OUTPUT_DIR/report.md"
    head -50 "$INPUT_DIR/raw/subdomains.txt" >> "$OUTPUT_DIR/report.md"
    if [[ $SUBDOMAINS -gt 50 ]]; then
        echo "... and $((SUBDOMAINS - 50)) more" >> "$OUTPUT_DIR/report.md"
    fi
    echo '```' >> "$OUTPUT_DIR/report.md"
else
    echo "_No subdomains found_" >> "$OUTPUT_DIR/report.md"
fi

cat >> "$OUTPUT_DIR/report.md" << EOF

---

## Live Hosts

EOF

if [[ -f "$INPUT_DIR/raw/alive_urls.txt" ]] && [[ -s "$INPUT_DIR/raw/alive_urls.txt" ]]; then
    echo '```' >> "$OUTPUT_DIR/report.md"
    head -30 "$INPUT_DIR/raw/alive_urls.txt" >> "$OUTPUT_DIR/report.md"
    if [[ $ALIVE_HOSTS -gt 30 ]]; then
        echo "... and $((ALIVE_HOSTS - 30)) more" >> "$OUTPUT_DIR/report.md"
    fi
    echo '```' >> "$OUTPUT_DIR/report.md"
else
    echo "_No live hosts found_" >> "$OUTPUT_DIR/report.md"
fi

cat >> "$OUTPUT_DIR/report.md" << EOF

---

## Vulnerabilities

EOF

if [[ -f "$INPUT_DIR/vulnerabilities/nuclei.json" ]] && [[ $VULNS -gt 0 ]]; then
    if command -v jq &> /dev/null; then
        jq -r '.[] | "- **\(.info.severity | ascii_upcase)**: \(.info.name) at \(.host)"' \
            "$INPUT_DIR/vulnerabilities/nuclei.json" 2>/dev/null | head -20 >> "$OUTPUT_DIR/report.md" || true
    else
        echo "See \`vulnerabilities/nuclei.json\` for details" >> "$OUTPUT_DIR/report.md"
    fi
else
    echo "_No vulnerabilities found_" >> "$OUTPUT_DIR/report.md"
fi

cat >> "$OUTPUT_DIR/report.md" << EOF

---

_Report generated by Smart Recon Automation Suite 2025_
EOF

# =============================================================================
# HTML REPORT
# =============================================================================

cat > "$OUTPUT_DIR/report.html" << 'HTMLHEAD'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recon Report</title>
    <style>
        :root {
            --bg-dark: #0d1117;
            --bg-card: #161b22;
            --text-primary: #c9d1d9;
            --text-secondary: #8b949e;
            --accent: #58a6ff;
            --success: #3fb950;
            --warning: #d29922;
            --danger: #f85149;
            --border: #30363d;
        }
        
        * { box-sizing: border-box; margin: 0; padding: 0; }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: var(--bg-dark);
            color: var(--text-primary);
            line-height: 1.6;
            padding: 2rem;
        }
        
        .container { max-width: 1200px; margin: 0 auto; }
        
        h1 {
            font-size: 2rem;
            margin-bottom: 0.5rem;
            background: linear-gradient(90deg, var(--accent), #a371f7);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        
        .subtitle { color: var(--text-secondary); margin-bottom: 2rem; }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }
        
        .stat-card {
            background: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1.5rem;
            text-align: center;
        }
        
        .stat-value {
            font-size: 2.5rem;
            font-weight: bold;
            color: var(--accent);
        }
        
        .stat-label { color: var(--text-secondary); }
        
        .section {
            background: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
        }
        
        .section h2 {
            font-size: 1.25rem;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid var(--border);
        }
        
        .data-list {
            max-height: 300px;
            overflow-y: auto;
            font-family: monospace;
            font-size: 0.875rem;
            background: var(--bg-dark);
            padding: 1rem;
            border-radius: 4px;
        }
        
        .data-list div { padding: 0.25rem 0; }
        
        .severity-critical { color: var(--danger); }
        .severity-high { color: #f0883e; }
        .severity-medium { color: var(--warning); }
        .severity-low { color: var(--success); }
        
        footer {
            text-align: center;
            color: var(--text-secondary);
            margin-top: 2rem;
            font-size: 0.875rem;
        }
    </style>
</head>
<body>
    <div class="container">
HTMLHEAD

cat >> "$OUTPUT_DIR/report.html" << EOF
        <h1>🔍 Recon Report: $TARGET</h1>
        <p class="subtitle">Generated on $DATE_HUMAN</p>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value">$SUBDOMAINS</div>
                <div class="stat-label">Subdomains</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">$ALIVE_HOSTS</div>
                <div class="stat-label">Live Hosts</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">$OPEN_PORTS</div>
                <div class="stat-label">Open Ports</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">$VULNS</div>
                <div class="stat-label">Vulnerabilities</div>
            </div>
        </div>
        
        <div class="section">
            <h2>📋 Subdomains</h2>
            <div class="data-list">
EOF

if [[ -f "$INPUT_DIR/raw/subdomains.txt" ]] && [[ -s "$INPUT_DIR/raw/subdomains.txt" ]]; then
    head -100 "$INPUT_DIR/raw/subdomains.txt" | while read -r line; do
        echo "                <div>$line</div>" >> "$OUTPUT_DIR/report.html"
    done
else
    echo "                <div>No subdomains found</div>" >> "$OUTPUT_DIR/report.html"
fi

cat >> "$OUTPUT_DIR/report.html" << EOF
            </div>
        </div>
        
        <div class="section">
            <h2>🌐 Live Hosts</h2>
            <div class="data-list">
EOF

if [[ -f "$INPUT_DIR/raw/alive_urls.txt" ]] && [[ -s "$INPUT_DIR/raw/alive_urls.txt" ]]; then
    head -50 "$INPUT_DIR/raw/alive_urls.txt" | while read -r line; do
        echo "                <div><a href=\"$line\" target=\"_blank\" style=\"color: var(--accent);\">$line</a></div>" >> "$OUTPUT_DIR/report.html"
    done
else
    echo "                <div>No live hosts found</div>" >> "$OUTPUT_DIR/report.html"
fi

cat >> "$OUTPUT_DIR/report.html" << 'HTMLFOOT'
            </div>
        </div>
        
        <footer>
            <p>Generated by Smart Recon Automation Suite 2025</p>
        </footer>
    </div>
</body>
</html>
HTMLFOOT

echo "[reporter] Reports generated:"
echo "  - $OUTPUT_DIR/report.json"
echo "  - $OUTPUT_DIR/report.md"
echo "  - $OUTPUT_DIR/report.html"
